### ISSUE TITLE
RollingHashのrand範囲の範囲修正

### ISSUE THREAD

**Issue by xryuseix** [masa-aa/Open-Folder#2]
randintの範囲が間違っていて，1%の確率で落ちるので修正しました．
あと一部リファクタリングを行いました．
https://gist.github.com/xryuseix/28cda90baa359dc88372b657d7aab629

こちらでverify済です
https://onlinejudge.u-aizu.ac.jp/solutions/problem/ALDS1_14_B/review/5126454/yui_nan/Python3

**Comment by masa-aa** [comment]
ありがとう修正したよ．
2点変更を加えた．
・modが2**62 -1 になっていたのを2**61 -1に修正
・従来のearly returnするcontainは競プロ的にあるとうれしいのでis_containという名前で追加したよ．

https://github.com/masa-aa/Open-Folder/blob/master/library_atcoder/%E6%96%87%E5%AD%97%E5%88%97/%E3%83%AD%E3%83%BC%E3%83%AA%E3%83%B3%E3%82%B0%E3%83%8F%E3%83%83%E3%82%B7%E3%83%A5.py
